Fixed crash when calling vibrate.
defold/extension-android pull request #2
Opened 2023-11-08 23:05 UTC by OscarLeif

Also added a custom manifest to add the vibrate permission.
The example crash this should make the extension work.

2023-11-09 08:02 UTC, britzl requested changes
See note about android manifest

2023-11-09 08:02 UTC, britzl commented on CustomManifest/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
The preferred way to add a permission needed by an extension is to add a manifest stub with the permission. This will then be merged into the main manifest when the extension builds. Here's an example from the camera extension:

https://github.com/defold/extension-camera/blob/master/camera/manifests/android/AndroidManifest.xml

So my recommendation is that you remove the `CustomManifest/AndroidManifest.xml` and replace it with a file in `androidnative/manifests/android/AndroidManifest.xml`

2023-11-09 20:38 UTC, OscarLeif commented on CustomManifest/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
Oh that's much better. Thanks.

2023-11-09 21:00 UTC, OscarLeif commented on CustomManifest/AndroidManifest.xml
> +<?xml version="1.0" encoding="utf-8"?>
Ok I already remove the Custom Manifest and setup a manifest inside the plugin folder.
I test on the phone and it's working fine.

2023-11-10 10:13 UTC, britzl approved these changes
Thanks!

2023-11-10 10:13 UTC, merged